version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt-preview
            rustup update
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Build x86
          command: cargo build --release --target=x86_64-unknown-linux-gnu
      - run:
          name: Build wasm32
          command: cargo build --release --target=wasm32-unknown-unknown
